### ISSUE TITLE
Hi, I find it's hard to train such a deep model

### ISSUE THREAD

**Issue by yiyuzhuang** [chengerr/Model-Guided-Deep-Hyperspectral-Image-Super-resolution#1]
As I was training model, it usually appears that the training loss gets 'Nan' value.
Could you please show me is there an adequate process for correcting problems identified in training? 
Thanks a lot!

**Comment by chengerr** [comment]
Yes , it is deep ,and that's why we add skip connections between modules of the proposed network.  Maybe you can check  your data processing.
