### ISSUE TITLE
Could you please show me how the Harvard data is processed to obtain the RGB image?

### ISSUE THREAD

**Issue by dusongcheng** [chengerr/Model-Guided-Deep-Hyperspectral-Image-Super-resolution#2]
Could you please show me how the Harvard data is processed to obtain the RGB image?

**Comment by chengerr** [comment]
RGB = X* P, where the shape of X is  W*H*31, P is 31*3.  We use P from paper '_Hyperspectral image super-resolution via non-negative structured sparse representation_'

**Comment by dusongcheng** [comment]
Thanks for your replying, I get P, but there are many important details in the process, such as normalization...which cause different on  test result. So could you  please share the code of getting RGB images.
