### ISSUE TITLE
关于相关的环境配置

### ISSUE THREAD

**Issue by zhihaofan** [chengerr/Model-Guided-Deep-Hyperspectral-Image-Super-resolution#3]
您好，请问相关的环境都是什么版本的？
我电脑的pytorch是1.10版的，然后运行该程序的时候报错，改了一部分，发现版本差别挺大的，然后使用您发的上篇的Mog-DUN这篇文章是1.01版的pytorch，我试了之后发现该版本没有双三次插值这个方法。我想知道相关的版本信息。
谢谢。

**Comment by chengerr** [comment]
1.3 or 1.5
